name: dindin_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  fl_chart: ^0.55.2
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  crypto: ^3.0.2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/
